{{- if .Values.additionalCA }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vouch.fullname" . }}-ca
  labels:
{{ include "vouch.labels" . | indent 4 }}
data:
  ca.crt: |
{{ .Values.additionalCA | indent 4}}
{{- end }}
