{{- $kubeTargetVersion := default .Capabilities.KubeVersion.GitVersion .Values.kubeTargetVersionOverride }}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "vouch.fullname" . -}}
{{- $ingressPaths := .Values.ingress.paths -}}
{{- if semverCompare ">=1.19-0" $kubeTargetVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $kubeTargetVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: {{ .Values.controller.ingress.apiVersion }}
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "vouch.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName  }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ tpl . $ | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ tpl . $ | quote }}
      http:
        paths:
  {{- range $ingressPaths }}
          - path: {{ . }}
            backend:
            {{- if semverCompare ">=1.19-0" $kubeTargetVersion }}
              service:
                name: {{ $fullName }}
                port:
                  name: http
            pathType: Prefix
            {{- else }}
              serviceName: {{ $fullName }}
              servicePort: http
            {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
