apiVersion: v1
kind: Service
metadata:
  name: {{ include "vouch.fullname" . }}
  labels:
{{ include "vouch.labels" . | indent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vouch.selectorLabels" . | nindent 4 }}
